### ISSUE TITLE
请教下如何使用bts客户端现有的websockets接口

### ISSUE THREAD

**Issue by cgafeng** [pch957/btsbots-wallet#1]
我大概看了下你的python代码，没看到使用websockets接口的地方。
我目前正在做一个移动端的钱包，也想使用websockets接口，但我还没看bts客户端的websockets如何使用，是不是ssl websockets的接口已经可以使用了，有没有调用的例子，python的也可以。
我的代码地址：https://github.com/cgafeng/btsMobileWallet

**Comment by pch957** [comment]
bts本身的 websocket 功能应该还没好吧。
我用 flask-ext-socketio 实现的 websocket 服务，在本机启动一个 http server + web socket server
web界面通过 http/web socekt 服务和钱包通信
